
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Multiple-api-demo 
  description: BS TEST
  annotations:
    github.com/project-slug: org-bs/backstage-k8s-demo
    circleci.com/project-slug: github/org-bs/backstage-k8s-demo
    sonarqube.org/project-key: org-bs/test
    jira/project-key: test
    sentry.io/project-slug: test
    datadoghq.com/dashboard-url: "https://example.com"
    backstage.io/techdocs-ref: dir:.
    opsgenie.com/team: test-team

spec:
  type: service
  lifecycle: production
  owner: global-devops
  system: global-devops
  providesApis:
     - Multiple-api-demo
     - Multiple-api-demo-2
     - Multiple-api-demo-3
 

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  title: Multiple-api-dem-title 
  name: Multiple-api-demo 
  description: Multiple-api-demo 
# annotations:
#   openapi/ref-basepath: ./
spec:
  type: openapi
  lifecycle: production
  owner: insights-engine
  definition:
    $openapi: ./openapi.yaml


--- 
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  title: Multiple-api-demo-2-title
  name: Multiple-api-demo-2
  description: Multiple-api-demo-2
# annotations:
#   openapi/ref-basepath: ./
spec:
  type: openapi
  lifecycle: production
  owner: insights-engine
  definition:
    $openapi: ./openapi-2.yaml


---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  title: Multiple-api-demo-3-title
  name: Multiple-api-demo-3
  description: Multiple-api-demo-3
# annotations:
#   openapi/ref-basepath: ./
spec:
  type: openapi
  lifecycle: production
  owner: insights-engine
  definition:
    $openapi: "https://github.com/org-bs/circclecitest/blob/backstage-integration/openapi.yaml"
