
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Multiple-api-demo 
  description: BS TEST
  annotations:
    github.com/project-slug: org-bs/backstage-k8s-demo
    circleci.com/project-slug: github/org-bs/backstage-k8s-demo
spec:
  type: service
  lifecycle: production
  owner: global-devops
  system: global-devops
 

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  title: Multiple-api-demo 
  name: Multiple-api-demo 
  description: Multiple-api-demo 
# annotations:
#   openapi/ref-basepath: ./
spec:
  type: openapi
  lifecycle: production
  owner: insights-engine
  definition:
    $openapi: ./openapi.yaml
